wrappid/guide-module

- app/components/styles-docs/StyleUtilitiesSamples.js
#32
Changed The text utility documentation according to the changes suggested by the testing team in issue no #32  "Resolves #32 ".
> docs: :memo: Text documentation related changes

- app/components/styles-docs/StyleUtilities.js
- app/components/styles-docs/StyleUtilitiesSamples.js
border radius issue and color related updates in styleUtilitiesSamples
Ref #30
> fix(core): :bug: border radius issue and color related updates

- .eslint/app/.eslintrc.js
- .eslint/service/.eslintrc.js
- .eslintrc.js
- .github/workflows/pr-guardrails.yml
- LICENSE
- app/components/component-docs/ComponentsMenu.js
- app/components/component-docs/navigation/CoreMenu.docs.js
- app/components/styles-docs/StyleUtilities.js
- app/components/styles-docs/StyleUtilitiesSamples.js
- lint-staged.config.js
- package-lock.json
- package.json
- service/functions/test.functions.js
Merge development branch into main branch
> Merge development into main

- .github/workflows/pr-guardrails.yml
- service/validations.registry.js
validation.registry import fix
---
> bug: import fix

- app/components/styles-docs/StyleUtilitiesSamples.js
overflow-x & overflow-y problem resolved by adding height and width.
Ref #34
> fix(core): :bug: overflow-x & overflow-y problem resolved

- app/components/styles-docs/StyleUtilitiesSamples.js
> CoreLink and handleClick added to Interaction's POINTER_EVENT.
> All classnames are aligned to center.
> StyleUtilitySamples Interaction related changes

- .github/workflows/auto-create-and-merge-pr.yml
- .husky/pre-commit
- .vscode/settings.json
- ATTRIBUTIONS.md
- app/styles/DefaultModuleStyles.js
- app/styles/LargeModuleStyles.js
- app/styles/MediumModuleStyles.js
- app/styles/SmallModuleStyles.js
- app/styles/XLargeModuleStyles.js
- app/styles/XXLargeModuleStyles.js
- package-lock.json
- package.json
- scripts/attributions.gen.js
> Wrpd refactor 95

- .github/workflows/auto-create-and-merge-pr.yml
- .husky/pre-commit
- .vscode/settings.json
- ATTRIBUTIONS.md
- app/styles/DefaultModuleStyles.js
- app/styles/LargeModuleStyles.js
- app/styles/MediumModuleStyles.js
- app/styles/SmallModuleStyles.js
- app/styles/XLargeModuleStyles.js
- app/styles/XXLargeModuleStyles.js
- package-lock.json
- package.json
- scripts/attributions.gen.js
> merge: from development branch

- .husky/pre-commit
ref: #95
merged into main and fixed eslint errors
---
> refactor: merged into main and fixed eslint errors

- app/styles/DefaultModuleStyles.js
- app/styles/LargeModuleStyles.js
- app/styles/MediumModuleStyles.js
- app/styles/SmallModuleStyles.js
- app/styles/XLargeModuleStyles.js
- app/styles/XXLargeModuleStyles.js
Correct the typo 
-app/styles/DefaultModuleStyles.js
-app/styles/LargeModuleStyles.js
-app/styles/MediumModuleStyles.js
-app/styles/SmallModuleStyles.js
-app/styles/XLargeModuleStyles.js
-app/styles/XXLargeModuleStyles.js
correct styles to style
---
> fix(global): :fire: correct the typo

- .vscode/settings.json
- app/components/component-docs/dataDisplay/CoreAvatar.docs.js
- app/components/component-docs/dataDisplay/CoreAvatarGroup.docs.js
- app/components/component-docs/dataDisplay/CoreBadge.docs.js
- app/components/styles-docs/StyleUtilities.js
- app/components/styles-docs/StyleUtilitiesSamples.js
Typos, Grammatical errors, spelling error and other minor documentation errors
> styling: basic ui patches

- app/components/CodeBlock.js
sample code overlapping problem resolved. added overflow auto to CodeBlock. #105 
---
> sample code overlapping problem resolved

- app/components/component-docs/layouts/SampleLayouts.js
- app/components/styles-docs/StyleUtilities.js
- app/routes.registry.js
> Wrpd enhancement 109

- app/components/layout-docs/LayoutViewer.js
layout zoom related changes
ref: #109
---
> fix(core): :bug: layout zoom

- app/components/layout-docs/LayoutViewer.js
layout zoom feature and some UI changes
ref: #109
---
> feat(core): :sparkles: layout zoom feature and some UI changes

- app/components/ComponentPropTypes.js
- app/components/ComponentProps.js
ref: #121
wrappid component's documentation UI changed
---
> docs(core): :lipstick: wrappid component's documentation UI

- app/components/styles-docs/Styles.js
- app/components/styles-docs/StylesSamples.js
added padding X1 to the entire page in guide/styles
ref: #115
---
> refactor(global): :recycle: added padding X1 to the entire page

- app/components/layout-docs/LayoutViewer.js
- app/components/styles-docs/Styles.js
- app/components/styles-docs/StylesSamples.js
radial and conic gradients added and bgDotted renamed to bgDot
radial and conic gradients added and bgDotted renamed to bgDot in guide module
ref: #115
---
> feat(global): :sparkles: radial and conic gradients added and bgDotted renamed to bgDot

- app/components/CodeBlock.js
- app/components/CodeSample.js
- app/components/ComponentPropTypes.js
- app/components/ComponentProps.js
- app/components/component-docs/Components.js
- app/components/component-docs/ComponentsMenu.js
add a right sidebar with mobile toggle in component.js file
---
> right sidebar toggle for mobile in component.js

- app/components/component-docs/Components.js
add CoreTOC, CoreAppBar and CoreMenu in wrappid documentation page 
ref: #132
---
> feat(core): :lipstick: add CoreTOC and CoreMenu in wr docs

- app/components/layout-docs/LayoutViewer.js
- app/routes.registry.js
key prop added to layoutViewer and styles layout removed in guide
ref: #115
---
> fix(global): :bug: key prop added to layoutViewer and styles layout removed

- app/components/styles-docs/Styles.js
- app/components/styles-docs/StylesSamples.js
line-height and word-spacing documentation added to styles package
ref: #115
---
> documentation: line-height and word-spacing documentation added

- app/components/styles-docs/StylesSamples.js
gradient aspect ratio set to 1:1, Cursor note added in guide/styles
ref: #115
---
> docs(core): :memo: gradient aspect ratio set to 1:1, Cursor note added

- app/components/CodeSample.js
- app/components/component-docs/feedback/CoreAlert.docs.js
corrected the 'OnClick' to 'onClick' props
ref: #139
---
> refactor(core): :recycle: corrected the 'OnClick' to 'onClick' props

- app/components/styles-docs/StylesSamples.js
tramsform rotate documentation related changes
ref: #115
---
> fix(global): :bug: tramsform rotate documentation related changes

- app/components/component-docs/inputs/forms/CoreForm.docs.js
> CoreForm sample documentation

- app/routes.registry.js
fix: :zap: layouts route shouldn't have any layout
removed layout for layouts route in route registry
Ref #139
---
> fix: :zap: layouts route shouldn't have any layout

- app/components/CodeBlock.js
new styles added
Ref: #167
---
> fix: :bug: CodeBlock text highlight not working

- CHANGELOG.md
- app/components/CodeBlock.js
- app/components/ComponentPropTypes.js
- app/components/ComponentProps.js
- package-lock.json
- package.json
component valid props now shows
#165
---
> fix(core): :bug: component valid props

- app/components/component-docs/dataDisplay/CoreChip.docs.js
This PR updates documentation of CoreChip
#172 
---
> docs: modify documentation for CoreChip

- app/components/component-docs/dataDisplay/CoreBadge.docs.js
documentation for CoreBadge
Ref: #170
---
> feat(global): :bug: documentation for CoreBadge

- app/components/component-docs/dataDisplay/CoreH1.docs.js
- app/components/component-docs/dataDisplay/CoreH2.docs.js
- app/components/component-docs/dataDisplay/CoreH3.docs.js
- app/components/component-docs/dataDisplay/CoreH4.docs.js
- app/components/component-docs/dataDisplay/CoreH5.docs.js
- app/components/component-docs/dataDisplay/CoreH6.docs.js
> enhancement: documentation for CoreH1,H2,H3,H4,H5,H6

- app/components/component-docs/dataDisplay/CoreListItem.docs.js
-error in CoreListItems has fixed
-the description was not present it has also been updated properly.
**Image
Ref: #183
> fix(core): :bug: error showing in CoreListItem

- app/components/component-docs/dataDisplay/CoreTypographyBody1.docs.js
- app/components/component-docs/dataDisplay/CoreTypographyBody2.docs.js
- app/components/component-docs/dataDisplay/CoreTypographyButton.docs.js
- app/components/component-docs/dataDisplay/CoreTypographyCaption.docs.js
- app/components/component-docs/dataDisplay/CoreTypographyOverline.docs.js
- app/components/component-docs/dataDisplay/CoreTypographySubtitle1.docs.js
- app/components/component-docs/dataDisplay/CoreTypographySubtitle2.docs.js
This PR updates documentation for all CoreTypograhy* components
#178
---
> docs(core): :memo: add typography documentation

- app/components/component-docs/dataDisplay/CoreTypographyBody1.docs.js
- app/components/component-docs/dataDisplay/CoreTypographyBody2.docs.js
- app/components/component-docs/dataDisplay/CoreTypographyButton.docs.js
- app/components/component-docs/dataDisplay/CoreTypographyCaption.docs.js
- app/components/component-docs/dataDisplay/CoreTypographyOverline.docs.js
- app/components/component-docs/dataDisplay/CoreTypographySubtitle1.docs.js
- app/components/component-docs/dataDisplay/CoreTypographySubtitle2.docs.js
add codeImport component in Coretypography* docs
#178
---
> docs(core): :memo: add CodeImport component in CoreTypography*

- app/components/component-docs/dataDisplay/CoreImage.docs.js
This PR fixes code sample indentation of CoreImage component
#186
---
> fix(core): :bug: codesample of CoreImage correction

- app/components/component-docs/dataDisplay/CoreDivider.docs.js
modify documentation for CoreDivider
Ref: #174
---
> docs(global): :memo: modify documentation for CoreDivider

- app/components/component-docs/dataDisplay/CoreListItem.docs.js
- app/components/component-docs/dataDisplay/CoreListItemButton.docs.js
-CoreListItemButton docoment was not present 
-CoreListItem docs there is comment present  has been fixed
**Image**
Ref: #191
> fix(core): :bug: corelistitembutton has been fixed and corelistitem document has been corrected

- app/components/component-docs/dataDisplay/CoreListItemSecondaryAction.docs.js
corelistitemsecondaryaction has been implemented successfully
**Image**
Ref: #202
> fix(core): :bug: corelistitemsecondaryaction has been implemented

- app/components/component-docs/dataDisplay/CoreListItemIcon.docs.js
the proper docomentation of CoreListItemIcon has been updated
**Image**
Ref: #193
> docs(core): :memo: update docomentation of CoreListItemIcon

- app/components/component-docs/feedback/CoreBackdrop.docs.js
fix CoreBackDrop documentation
Ref: #200
---
> docs(global): :memo: fix CoreBackDrop documentation

- app/components/component-docs/dataDisplay/CoreListItemAvatar.docs.js
-the docomentation was not present has been updated
-it was showing not working - by using the sample code the user can understand how it works
**Image**
Ref: #189
> fix(core): :bug: the docomentation is not present has been updated

- app/components/component-docs/feedback/CoreAlert.docs.js
update documentation for CoreAlert
Ref: #198
---
> docs(global): :memo: update documentation for CoreAlert

- app/components/component-docs/dataDisplay/CoreTooltip.docs.js
> enhancement: CoreTooltip Documentation  

- app/components/component-docs/dataDisplay/CoreAvatar.docs.js
> bug: fix documentation for CoreAvatar 

- app/components/component-docs/dataDisplay/CoreLabel.docs.js
CoreLabel documentation with sample added.
#207
---
> docs(core): :memo: add CoreLabel documentation

- app/components/component-docs/dataDisplay/CoreListSubheader.docs.js
CoreListSubheader documentation has been updated
**Image**
Ref: #205
> docs(core): 📝CoreListSubheader documentation has been updated

- app/components/component-docs/feedback/CoreCircularProgress.docs.js
> docs: CoreCircularProgress documentation
